name: ebm_gh200
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - certifi=2025.6.15
  - icu=75.1
  - ld_impl_linux-aarch64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - nodejs=22.13.0
  - openssl=3.5.1
  - pip=25.0.1
  - python=3.11.12
  - readline=8.2
  - setuptools=78.1.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - zlib=1.3.1
  - pip:
      - absl-py==2.2.2
      - annotated-types==0.7.0
      - beautifulsoup4==4.13.3
      - charset-normalizer==3.4.1
      - click==8.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - filelock==3.16.1
      - fsspec==2024.10.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - jinja2==3.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.1.2
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.0.0
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pysocks==1.7.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.5.3
      - scipy==1.15.2
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.6
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - timm==1.0.15
      - torch==2.7.0.dev20250310+cu126
      - torch-fidelity==0.4.0b0
      - torchaudio==2.6.0.dev20250313
      - torchvision==0.22.0.dev20250313
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - wandb==0.19.9
      - werkzeug==3.1.3
